# Site settings
title: Pure's app
email: me@pureapp.in.th
description: เว็บนี้คือบล็อกส่วนตัวของเพียว (ภัคพล พงษ์ทวี) เขียนขึ้นเพื่อเผยแพร่ ความรู้และโปรแกรมที่สร้างขึ้น ผมหวังว่าทุกท่านที่เข้ามาจะได้รับประโยชน์ไม่มากก็น้อย
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pureapp.in.th" # the base hostname & protocol for your site
permalink: /:year/:month/:title.html
social:
  gplus: 113820425408268226106
  fb: 100000131794195
  fbapps: 351070565012663
  twitter: "@PakkaponPH"
include:      [".htaccess"]
# paginate settings
paginate: 5
paginate_path: "/page/:num"
# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
