# Site settings
title: Pure's app
email: me@pureapp.in.th
description: เว็บนี้คือบล็อกส่วนตัวของเพียว (ภัคพล พงษ์ทวี) เขียนขึ้นเพื่อเผยแพร่ ความรู้และโปรแกรมที่สร้างขึ้น ผมหวังว่าทุกท่านที่เข้ามาจะได้รับประโยชน์ไม่มากก็น้อย
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pureapp.in.th" # the base hostname & protocol for your site
repo: https://github.com/pureexe/www.pureapp.in.th # repo path for amp support
permalink: /:year/:month/:title.html
author: ภัคพล พงษ์ทวี
publisher: Pure's app
social:
  gplus: 113820425408268226106
  fb: 100000131794195
  fbapps: 351070565012663
  twitter: "@PakkaponPH"
# paginate settings
paginate: 5
paginate_path: "/page/:num"
# Build settings
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
month_name:
  - มกราคม
  - กุมภาพันธ์
  - มีนาคม
  - เมษายน
  - พฤษภาคม
  - มิถุนายน
  - กรกฏาคม
  - สิงหาคม
  - กันยายน
  - ตุลาคม
  - พฤศจิกายน
  - ธันวาคม
tag_name:
  announcement: ประกาศ
  computer: คอมพิวเตอร์
  diary: ชีวิตประจำวัน
  mathematics: คณิตศาสตร์
  review: รีวิว
  science: วิทยาศาสตร์
